services:
  - type: web
    name: flood-warning-nadma
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
